package model.entities;
// Generated 23/01/2014 14:28:10 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private Integer idComentario;
     private Usuario usuarioByUsuario;
     private Usuario usuarioByModeradoPor;
     private Publicacion publicacion;
     private String titulo;
     private String contenido;
     private Date fechaSubida;
     private Date fechaBaja;
     private Set sancions = new HashSet(0);

    public Comentario() {
    }

	
    public Comentario(Usuario usuarioByUsuario, Publicacion publicacion) {
        this.usuarioByUsuario = usuarioByUsuario;
        this.publicacion = publicacion;
    }
    public Comentario(Usuario usuarioByUsuario, Usuario usuarioByModeradoPor, Publicacion publicacion, String titulo, String contenido, Date fechaSubida, Date fechaBaja, Set sancions) {
       this.usuarioByUsuario = usuarioByUsuario;
       this.usuarioByModeradoPor = usuarioByModeradoPor;
       this.publicacion = publicacion;
       this.titulo = titulo;
       this.contenido = contenido;
       this.fechaSubida = fechaSubida;
       this.fechaBaja = fechaBaja;
       this.sancions = sancions;
    }
   
    public Integer getIdComentario() {
        return this.idComentario;
    }
    
    public void setIdComentario(Integer idComentario) {
        this.idComentario = idComentario;
    }
    public Usuario getUsuarioByUsuario() {
        return this.usuarioByUsuario;
    }
    
    public void setUsuarioByUsuario(Usuario usuarioByUsuario) {
        this.usuarioByUsuario = usuarioByUsuario;
    }
    public Usuario getUsuarioByModeradoPor() {
        return this.usuarioByModeradoPor;
    }
    
    public void setUsuarioByModeradoPor(Usuario usuarioByModeradoPor) {
        this.usuarioByModeradoPor = usuarioByModeradoPor;
    }
    public Publicacion getPublicacion() {
        return this.publicacion;
    }
    
    public void setPublicacion(Publicacion publicacion) {
        this.publicacion = publicacion;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public Date getFechaSubida() {
        return this.fechaSubida;
    }
    
    public void setFechaSubida(Date fechaSubida) {
        this.fechaSubida = fechaSubida;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public Set getSancions() {
        return this.sancions;
    }
    
    public void setSancions(Set sancions) {
        this.sancions = sancions;
    }




}


