package model.entities;
// Generated 23/01/2014 14:28:10 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tag generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private Integer idTag;
     private String texto;
     private Integer cantidad;
     private Set publicacions = new HashSet(0);

    public Tag() {
    }

    public Tag(String texto, Integer cantidad, Set publicacions) {
       this.texto = texto;
       this.cantidad = cantidad;
       this.publicacions = publicacions;
    }
   
    public Integer getIdTag() {
        return this.idTag;
    }
    
    public void setIdTag(Integer idTag) {
        this.idTag = idTag;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Set getPublicacions() {
        return this.publicacions;
    }
    
    public void setPublicacions(Set publicacions) {
        this.publicacions = publicacions;
    }




}


