package model.entities;
// Generated 23/01/2014 14:28:10 by Hibernate Tools 3.6.0

import java.util.Collection;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.ManyToMany;

/**
 * Tag generated by hbm2java
 */
@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public class Tag implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    private Integer idTag;
    private String texto;
    private Integer cantidad;

    @ManyToMany
    private Collection<Publicacion> publicacions;
    
    public Tag() {
    }

    public Tag(String texto) {
        this.texto = texto;
    }

    public Tag(String texto, Integer cantidad, Set publicacions) {
        this.texto = texto;
        this.cantidad = cantidad;
        this.publicacions = publicacions;
    }
    
    public boolean equals(Object t){
        return ((Tag) t).getTexto().equals(this.getTexto());
    }

    public Integer getIdTag() {
        return this.idTag;
    }

    public void setIdTag(Integer idTag) {
        this.idTag = idTag;
    }

    public String getTexto() {
        return this.texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }

    public Integer getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    public void setPublicacions(Set publicacions) {
        this.publicacions = publicacions;
    }

    public Collection<Publicacion> getPublicacions() {
        return publicacions;
    }

    public void setPublicacions(Collection<Publicacion> publicacions) {
        this.publicacions = publicacions;
    }


}
