package model.entities;
// Generated 23/01/2014 14:28:10 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String apellido;
     private String dni;
     private String legajo;
     private String mail;
     private String clave;
     private Boolean moderador;
     private Date fechaFinSancion;
     private String avatar;
     private Set publicacionsForModeradoPor = new HashSet(0);
     private Set comentariosForUsuario = new HashSet(0);
     private Set votos = new HashSet(0);
     private Set comentariosForModeradoPor = new HashSet(0);
     private Set sistemas = new HashSet(0);
     private Set publicacionsForUsuarioPublicador = new HashSet(0);
     private Set eventos = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String nombre, String apellido, String dni, String legajo, String mail, String clave, Boolean moderador, Date fechaFinSancion, String avatar, Set publicacionsForModeradoPor, Set comentariosForUsuario, Set votos, Set comentariosForModeradoPor, Set sistemas, Set publicacionsForUsuarioPublicador, Set eventos) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.legajo = legajo;
       this.mail = mail;
       this.clave = clave;
       this.moderador = moderador;
       this.fechaFinSancion = fechaFinSancion;
       this.avatar = avatar;
       this.publicacionsForModeradoPor = publicacionsForModeradoPor;
       this.comentariosForUsuario = comentariosForUsuario;
       this.votos = votos;
       this.comentariosForModeradoPor = comentariosForModeradoPor;
       this.sistemas = sistemas;
       this.publicacionsForUsuarioPublicador = publicacionsForUsuarioPublicador;
       this.eventos = eventos;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getLegajo() {
        return this.legajo;
    }
    
    public void setLegajo(String legajo) {
        this.legajo = legajo;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Boolean getModerador() {
        return this.moderador;
    }
    
    public void setModerador(Boolean moderador) {
        this.moderador = moderador;
    }
    public Date getFechaFinSancion() {
        return this.fechaFinSancion;
    }
    
    public void setFechaFinSancion(Date fechaFinSancion) {
        this.fechaFinSancion = fechaFinSancion;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public Set getPublicacionsForModeradoPor() {
        return this.publicacionsForModeradoPor;
    }
    
    public void setPublicacionsForModeradoPor(Set publicacionsForModeradoPor) {
        this.publicacionsForModeradoPor = publicacionsForModeradoPor;
    }
    public Set getComentariosForUsuario() {
        return this.comentariosForUsuario;
    }
    
    public void setComentariosForUsuario(Set comentariosForUsuario) {
        this.comentariosForUsuario = comentariosForUsuario;
    }
    public Set getVotos() {
        return this.votos;
    }
    
    public void setVotos(Set votos) {
        this.votos = votos;
    }
    public Set getComentariosForModeradoPor() {
        return this.comentariosForModeradoPor;
    }
    
    public void setComentariosForModeradoPor(Set comentariosForModeradoPor) {
        this.comentariosForModeradoPor = comentariosForModeradoPor;
    }
    public Set getSistemas() {
        return this.sistemas;
    }
    
    public void setSistemas(Set sistemas) {
        this.sistemas = sistemas;
    }
    public Set getPublicacionsForUsuarioPublicador() {
        return this.publicacionsForUsuarioPublicador;
    }
    
    public void setPublicacionsForUsuarioPublicador(Set publicacionsForUsuarioPublicador) {
        this.publicacionsForUsuarioPublicador = publicacionsForUsuarioPublicador;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }




}


