package model.entities;
// Generated 23/01/2014 14:28:10 by Hibernate Tools 3.6.0



/**
 * Voto generated by hbm2java
 */
public class Voto  implements java.io.Serializable {


     private Integer idVoto;
     private Publicacion publicacion;
     private Usuario usuario;

    public Voto() {
    }

    public Voto(Publicacion publicacion, Usuario usuario) {
       this.publicacion = publicacion;
       this.usuario = usuario;
    }
   
    public Integer getIdVoto() {
        return this.idVoto;
    }
    
    public void setIdVoto(Integer idVoto) {
        this.idVoto = idVoto;
    }
    public Publicacion getPublicacion() {
        return this.publicacion;
    }
    
    public void setPublicacion(Publicacion publicacion) {
        this.publicacion = publicacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


